###show all fields
GET http://localhost:8080/api/fields
###create a new field
POST http://localhost:8080/api/fields
Content-Type: application/json

{
    "type": "Futbol 11",
    "status": false,
    "grill": false,
    "price": 150,
    "imageUrl": "https://recreasport.com/wp-content/uploads/2017/04/IMAG0030.jpg"
}
###show a field by id
GET http://localhost:8080/api/fields/654e94dbf6b2eafc6ddcea86
###update a field by PUT method
PUT http://localhost:8080/api/fields/53490800-2a59-48e3-897a-d8039bebfc36
Content-Type: application/json

{
    "type": "Futbol 6",
    "status": true,
    "dimentions": "12x17"
}
###update a field by PATCH method
PATCH http://localhost:8080/api/fields/654e97fff6b2eafc6ddcea89
Content-Type: application/json

{
    "status": true
}
###delete a field
DELETE http://localhost:8080/api/fields/654e9ccfb0e6222121bc67b0